spring.application.name=journalApp

# MongoDB Atlas Connection String
spring.mongodb.uri=mongodb+srv://journal_db:journal_db@cluster0.25jlvga.mongodb.net/?appName=Cluster0

#spring.data.mongodb.auto-index-creation=true

# Optional: specifically naming the database
#spring.data.mongodb.database=journal_db