spring.application.name=journalApp

# MongoDB Atlas Connection String
spring.data.mongodb.uri=mongodb+srv://journal_db:journal_db@cluster0.25jlvga.mongodb.net/journal_db?retryWrites=true&w=majority
spring.data.mongodb.database=journal_db

#spring.data.mongodb.auto-index-creation=true

# Optional: specifically naming the database
#spring.data.mongodb.database=journal_db